import type { ConfigurableBaseRun } from "@/types/game";

export const BASE_RUN_KNIGHT: ConfigurableBaseRun = {
  health: { value: 50, max: 50 },
  gold: 3,
  type: "knight",
  reels: [
    [
      "Shield",
      "Sword",
      "Sword",
      "Sleep",
      "Sword",
      "Shield",
      "Sleep",
      "Shield",
      "Sword",
      "Coin",
    ],
    [
      "Sword",
      "Coin",
      "Sleep",
      "Shield",
      "Shield",
      "Sleep",
      "Sword",
      "Sleep",
      "Sleep",
      "Sword",
    ],
    [
      "Sleep",
      "Shield",
      "Sleep",
      "Sleep",
      "Sword",
      "Sleep",
      "Sleep",
      "Sword",
      "Sleep",
      "Shield",
    ],
  ],
};
